config/routes.rb
Rails.application.routes.draw do
  resources :vehiculos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  root 'home#index' 

end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :agencia
  belongs_to :segmento
  belongs_to :dpto_mendoza
  belongs_to :marca
  belongs_to :modelo
  has_many :fotos, dependent: :destroy
  accepts_nested_attributes_for :fotos, :reject_if => :all_blank, :allow_destroy => true

  validates_presence_of   :dpto_mendoza_id
  # validates_presence_of   :titulo
  validates_presence_of   :marca
  validates_presence_of   :modeloCustom
  validates_presence_of   :anio
  validates_presence_of   :precio
  validates_presence_of   :combustible
  validates_presence_of   :kilometraje
  validates_presence_of   :condicion
  
  # HACER: Ver validaciones de imagenes con paperclip, y realizar validaciones que faltan, como la regex para el modelo del vehículo
  # HACER: Acordar cuales son las validaciones obligatorias en el primer paso, y realizar seeds para poblar la db

  has_attached_file :foto_ppal, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/missing.jpg"
  validates_attachment_content_type :foto_ppal, :content_type => /\Aimage\/.*\Z/
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  before_action :set_vehiculo, only: [:show, :edit, :update, :destroy]
  before_action :set_empty_vehiculo, only: [:index]
  # GET /vehiculos
  # GET /vehiculos.json
  def index
    

    if params[:vehiculo]
      @vehiculo = Vehiculo.new(vehiculo_params)

      # obtener el paramtero segmento y filtrar la busqueda
      @segmento = params[:vehiculo]['segmento_id']
      if @segmento.blank?
        @vehiculos = Vehiculo.all
      else
        @vehiculos = Vehiculo.where(segmento_id: @segmento)
      end

      # paginar todos los vehiculos
      @vehiculos = @vehiculos.paginate(:page => params[:page], :per_page => 4)

      # PRECIO
      # obtener el valor maximo
      @max = @vehiculos.order(precio: :desc).first
      unless @max.blank?
        params[:precioMax_query] = @max.precio
      end
      # Filtrado por precio
      @precioMin = params[:precioMin]
      @precioMax = params[:precioMax]
      unless @precioMin.blank? and @precioMax.blank?
        @vehiculos = @vehiculos.where(precio: (@precioMin.to_f)..(@precioMax.to_f))
      end

      #COMBUSTIBLE
      @combustible = params[:vehiculo][:combustible]
      unless @combustible.blank?
        @arrayCombustible = @combustible.split(",")
        @aux = []
        @arrayCombustible.each do |e| 
          if e == "GNC"
            @aux = @aux + @vehiculos.where('combustible LIKE ?', "%#{e}%")
          else
            @aux = @aux + @vehiculos.where(combustible: e)
          end
        end
        @vehiculos = @aux
      end
    else
      @vehiculos = Vehiculo.all
      @vehiculos = @vehiculos.paginate(:page => params[:page], :per_page => 4)
      # obtener el valor maximo
      @max = @vehiculos.order(precio: :desc).first
      unless @max.blank?
        params[:precioMax_query] = @max.precio
      end
    end
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.json
  def show
  end

  # GET /vehiculos/new
  def new
    @vehiculo = Vehiculo.new
    segmento = params[:segmento]
    @caracteristicas_equipamiento = Caracteristica.where(segmento_id: segmento, tipo: 'equipamiento')
    @caracteristicas_seguridad = Caracteristica.where(segmento_id: segmento, tipo: 'seguridad')
    @caracteristicas_exterior = Caracteristica.where(segmento_id: segmento, tipo: 'exterior')
  end

  # GET /vehiculos/1/edit
  def edit
  end

  # POST /vehiculos
  # POST /vehiculos.json
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)
    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @vehiculo }
      else
        format.html { render :new }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehiculos/1
  # PATCH/PUT /vehiculos/1.json
  def update
    respond_to do |format|
      if @vehiculo.update(vehiculo_params)
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.json
  def destroy
    @vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to vehiculos_url, notice: 'Vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empty_vehiculo
      @vehiculo = Vehiculo.new
    end

    def set_vehiculo
      @vehiculo = Vehiculo.find(params[:id])
      segmento = @vehiculo.segmento_id
      @caracteristicas_equipamiento = Caracteristica.where(tipo: 'equipamiento', segmento_id: segmento)
      @caracteristicas_seguridad = Caracteristica.where(tipo: 'seguridad', segmento_id: segmento)
      @caracteristicas_exterior = Caracteristica.where(tipo: 'exterior', segmento_id: segmento)
      @split_equipamiento = @vehiculo.equipamiento.split(",")
      @split_seguridad = @vehiculo.seguridad.split(",")
      @split_exterior = @vehiculo.exterior.split(",")
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def vehiculo_params
      params.require(:vehiculo).permit(:usuario_id, :agencia_id, :segmento_id, :dpto_mendoza_id, :marca_id, :modelo_id, :modeloCustom, :titulo, :anio, :kilometraje, :combustible, :precio, :condicion, :comentario, :destacado, :principal, :denunciado, :alta, :equipamiento, :seguridad, :exterior, :foto_ppal, fotos_attributes: [:id, :descripciom, :imagen, :_destroy])
    end
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/vehiculos/_caracteristicas.html.erb
<div class="row">
  <div class="col-xs-6 col-md-4">
    <!-- EQUIPAMIENTO -->
    <h4>Equipamiento</h4>
    <% if @vehiculo.id %>
      <% @caracteristicas_equipamiento.each do |b| %>
        <% if @split_equipamiento.include?(b.nombre) %>
          <div class="checkbox">
            <label>
            <input type='checkbox' value='<%= b.nombre %>' class="array_equipamiento" checked><%= b.nombre %>
            </label>
          </div>
        <% else %>
        <div class="checkbox">
            <label>
            <input type='checkbox' value='<%= b.nombre %>' class="array_equipamiento" ><%= b.nombre %>
          </label>
        </div>
        <% end %>
      <% end %>
    <% else %>
      <% @caracteristicas_equipamiento.each do |b| %>
        
          <div class="checkbox">
              <label>
              <input type='checkbox' value='<%= b.nombre %>' class="array_equipamiento" ><%= b.nombre %>
              </label>
          </div>
        
      <% end %>
    <% end %>
  </div>
  <div class="col-xs-6 col-md-4">
    <!-- SEGURIDAD -->
    <h4>Seguridad</h4>
    <% if @vehiculo.id %>
      <% @caracteristicas_seguridad.each do |b| %>
        <% if @split_seguridad.include?(b.nombre) %>
          <div class="checkbox">
            <label>
            <input type='checkbox' value='<%= b.nombre %>' class="array_seguridad" checked><%= b.nombre %>
            </label>
          </div>
        <% else %>
        <div class="checkbox">
            <label>
            <input type='checkbox' value='<%= b.nombre %>' class="array_seguridad" ><%= b.nombre %>
          </label>
        </div>
        <% end %>
      <% end %>
    <% else %>
      <% @caracteristicas_seguridad.each do |b| %>
        
          <div class="checkbox">
              <label>
              <input type='checkbox' value='<%= b.nombre %>' class="array_seguridad" ><%= b.nombre %>
              </label>
          </div>
        
      <% end %>
    <% end %>
  </div>
  <div class="col-xs-6 col-md-4">
    <!-- EXTERIOR -->
    <h4>Exterior</h4>
    <% if @vehiculo.id %>
      <% @caracteristicas_exterior.each do |b| %>
        <% if @split_exterior.include?(b.nombre) %>
          <div class="checkbox">
            <label>
            <input type='checkbox' value='<%= b.nombre %>' class="array_exterior" checked><%= b.nombre %>
            </label>
          </div>
        <% else %>
        <div class="checkbox">
            <label>
            <input type='checkbox' value='<%= b.nombre %>' class="array_exterior" ><%= b.nombre %>
          </label>
        </div>
        <% end %>
      <% end %>
    <% else %>
      <% @caracteristicas_exterior.each do |b| %>
        
          <div class="checkbox">
              <label>
              <input type='checkbox' value='<%= b.nombre %>' class="array_exterior" ><%= b.nombre %>
              </label>
          </div>
        
      <% end %>
    <% end %>
  </div>
</div>

app/views/vehiculos/_form.html.erb
<div class="container margin-container bg-white">

  <div class="row header-form">
    <div class="col-xs-push-1 col-xs-10 text-center">
      <h2 class="h-padding">Publicar Vehículo</h2>
    </div>
  </div>
  <div class="row">
    <%= simple_form_for @vehiculo, :html => {multipart: true, id: 'form_new'}, defaults: { input_html: { class: 'form-control' }, label: false } do |f| %>

    
    <div class="col-xs-12 col-md-offset-2 col-md-8">
      <legend id='titulo_paso'>Datos del Vehículo</legend>
      <% if @vehiculo.errors.any? %>
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <h2><%= pluralize(@vehiculo.errors.count, "error") %> prohibited this vehiculo from being saved:</h2>

          <ul>
          <% @vehiculo.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>

    <div class="col-xs-offset-1 col-xs-10 col-md-offset-3 col-md-6">
      <div id="paso1">

        <!-- CAPTURA USUARIO Y COPIA CON JQUERY -->
        <% if !@vehiculo.id %>
          <div class="form-group">
            <%= f.input :usuario_id, as: :hidden %>
            <input class="numeric integer optional disabled form-control hidden" id="usuario_id" type="number" value="<%= current_usuario.id %>">
          </div>
        <% end %>

        <!-- SEGMENTO ESCONDIDO / SETEADO URL JQUERY -->
        <div class="form-group">
          <%= f.association  :segmento, label_method: :nombre, value_method: :id, as: :hidden %>
        </div>

        <div class="form-group">
          <label>Ubicacion</label>
          <%= f.association  :dpto_mendoza, label_method: :nombre, value_method: :id %>
        </div>

        <!-- TITULO -->
        <div class="row">
          <fieldset class="">
            <legend class="">Título</legend>
          <div class="col-xs-12 col-md-3">
            <div class="form-group">
            <label>Marca</label>
            <%= f.association  :marca, label_method: :nombre, value_method: :id %>
          </div>
          </div>
          <div class="col-xs-12 col-md-6">
            <div class="form-group">
              <label>Modelo</label>
              <%= f.input :modeloCustom %>
            </div>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="form-group">
            <label>Año</label>
            <%= f.input :anio, collection: 1900..2014 %>
            </div>
          </div>
          <div class="col-xs-12">
            <label>Vista previa: Título de la publicación</label>
            <input type="text" id="titulo_prev" class="form-control", placeholder='Ej: [marca] Peugeot [modelo] 207 Compact 5P [año] 2014' disabled >
            <%= f.input :titulo, as: :hidden %>
          </div>
        </fieldset>
        </div>
        
        <!-- CARCATERISTICAS PRINCIPALES -->
        <div class="row">
          <fieldset class="">
            <legend class="">Características Principales</legend>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
              <label>Precio</label>
              <%= f.input :precio, input_html: { value: '0' } %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
              <label>Combustible</label>
              <%= f.input :combustible, as: :select, collection: ['Nafta', 'Nafta | GNC', 'Diesel', 'Diesel | GNC', 'GNC', 'Otro'] %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
              <label>Kilometraje</label>
              <%= f.input :kilometraje, input_html: { value: '0' } %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="form-group">
              <label>Condición</label>
              <%= f.input :condicion, as: :select, collection: ['Nuevo | Okm', 'Usado'] %>
            </div>
          </div>
          </fieldset>
        </div>
      </div>

      <div id="paso2">
  
        <%= render 'caracteristicas'  %>

        <div class="form-group">
          <%= f.input :equipamiento, as: :hidden %>
        </div>
        <div class="form-group">
          <%= f.input :seguridad, as: :hidden %>
        </div>
        <div class="form-group">
          <%= f.input :exterior, as: :hidden %>
        </div>
        <div class="form-group">
          <label>Comentario</label>
          <%= f.input :comentario, placeholder: 'Escribe un comentario si lo necesitas' %>
        </div>

      </div>

      <div id="paso3">
        <!-- FOTO PPAL -->
        <fieldset class="">
            <legend class="">Foto principal</legend>
            <div class="form-group">
              <%= f.input :foto_ppal, class: 'filestyle', id: 'foto_ppal' %>
            </div>
        </fieldset>
        <!-- FOTOS / FORM ANIDADO -->
        <fieldset class="">
            <legend class="">Fotos secundarias</legend>
            <div class="row">
                <%= f.simple_fields_for :fotos do |foto| %>
                  <%= render 'foto_fields', :f => foto %>
                <% end %>
            </div>
            <div class="row">
                 <div class="col-xs-12">
                   <%= link_to_add_association 'Agregar foto', f, :fotos,  class: 'btn btn-primary', id: 'agregar' %>
                   <%= link_to_remove_association "Eliminar foto", f, class: 'btn btn-primary', id: 'borrar' %>
                 </div>      
            </div>
        </fieldset>
      </div>
      <!-- INPUT ALTA / MANEJO DEL SUBMIT -->
      <div class="form-group">
          <%= f.input :alta, required: true, as: :hidden %>
      </div>
      <!-- BOTONES -->
      <hr>
      <div class="form-group">
          <button type='submit' id='continuar_paso1' class='btn btn-primary'>Continuar&nbsp;&nbsp;<span class="glyphicon glyphicon-arrow-right"></span></button>
          <a id='volver_paso1' class='btn btn-default'>Paso 1</a>
          <button type='submit' id='continuar_paso2' class='btn btn-primary'>Continuar&nbsp;&nbsp;<span class="glyphicon glyphicon-arrow-right"></span></button>
          <a id='volver_paso2' class='btn btn-default'>Paso 2</a>
          <%= f.button :submit, "Publicar", class: 'btn btn-success', id: 'publicar' %>
      </div> 
    </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'vehiculos', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'bootstrap-filestyle.min', 'data-turbolinks-track' => true %>

app/views/vehiculos/_foto_fields.html.erb
<div class="nested-fields">
	<div class="col-xs-12 col-sm-6 col-md-6">
		<div class="form-group">
			<label for="dscripciom">Descripción</label>
			<%= f.input :descripciom, placeholder: 'Ej: lateral, frente, interior...' %>
		</div>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6">
		<div class="form-group">
			<label for="imagen">Foto</label>
			<%= f.input :imagen, class: 'filestyle' %>	
		</div>
	</div>	
</div>

<script>
	$(":file").filestyle({buttonName: "btn-primary", buttonText: "Seleccionar", icon: false }); 
</script>

app/views/vehiculos/edit.html.erb
<%= render 'form' %>

app/views/vehiculos/index.html.erb
<div class="container margin-container">
  <div class="row">
    <div class="col-xs-12 col-md-3 filters-container">
      <div class="row">
        <%= simple_form_for @vehiculo, method: 'get', defaults: { input_html: { class: 'form-control' }, label: false } do |f| %>
        <!-- Header Reset -->
        <div class="col-xs-4 col-md-12">
          <div class="row filter" >
            <div class="col-xs-12 header-ppal">
              <h3><span class="glyphicon glyphicon-ok-sign"></span>Filtros Aplicados</h3>
            </div>
            <div class="col-xs-offset-1 col-xs-10">
              <p class="alert alert-info" role="alert">Algun filtro</p>
              <p class="alert alert-info" role="alert">Otro filtro</p>
              <a class="btn btn-primary center-block" id="eliminar_todos"><span class="glyphicon glyphicon-trash"></span>&nbsp;Eliminar Todos</a>
            </div>
          </div>
        </div>
        <!-- SEGMENTOS -->
        <div class="col-xs-4 col-md-12">
          <div class="row filter">
            <div class="col-xs-12 filter-header">
              <h3><span class="glyphicon glyphicon-filter"></span>Tipo de vehículo</h3>
            </div>
            <div class="col-xs-12">
              <%= f.association :segmento, as: :select, label_method: :nombre, value_method: :id, prompt: 'Todos'%>
            </div>
          </div>
        </div>
        <!-- MARCAS -->
        <div class="col-xs-4 col-md-12">
          <div class="row filter">
            <div class="col-xs-12 filter-header">
              <h3><span class="glyphicon glyphicon-filter"></span>Marca</h3>
            </div>
            <div class="col-xs-12">
              <%= f.association :marca, as: :select, label_method: :nombre, value_method: :id, prompt: 'Todas' %>
            </div>
          </div>
        </div>
        <!-- PECIO / KM / AÑO -->
        <div class="col-xs-4 col-md-12">
          <div class="row filter">
            <div class="col-xs-12 filter-header">
              <h3><span class="glyphicon glyphicon-filter"></span>Precio</h3>
            </div>
            <div class="col-xs-12">
              <input type="text" class="span2 form-control">
              <!-- Input para setear valor maximo de precio -->
              <%= text_field_tag :precioMax_query, params[:precioMax_query], id: 'precioMax_query', class: 'form-control hidden'%>
            </div>
            <div class="col-xs-6">
              <div class="form-group">
                <label for="">Min</label>
                <%= text_field_tag :precioMin, params[:precioMin], id: 'precioMin', class: 'form-control', placeholder: 'Minimo' %>
              </div>
            </div>
            <div class="col-xs-6">
              <div class="form-group">
                <label for="">Max</label>
                <%= text_field_tag :precioMax, params[:precioMax], id: 'precioMax', class: 'form-control', placeholder: 'Maximo' %>
              </div>
            </div>
          </div>
          <div class="row filter">
            <div class="col-xs-12 filter-header">
              <h3><span class="glyphicon glyphicon-filter"></span>Condición</h3>
            </div>
            <div class="col-xs-12">
              <%= f.input :condicion, as: :select, collection: ['Nuevo | Okm', 'Usado'], prompt: 'Todas' %>
            </div>
          </div>
        </div>
        <!-- COMBUSTIBKE -->
        <div class="col-xs-4 col-md-12">
          <div class="row filter">
            <div class="col-xs-12 filter-header">
              <h3><span class="glyphicon glyphicon-filter"></span>Combustible</h3>
            </div>
            <div class="col-xs-12">
              <div class="checkbox">
                <label>
                <input type='checkbox' value='Nafta' class="array_combustible">Nafta
                </label><br>
                <label>
                <input type='checkbox' value='Diesel' class="array_combustible">Diesel
                </label><br>
                <label>
                <input type='checkbox' value='GNC' class="array_combustible">GNC
                </label><br>
                <label>
                <input type='checkbox' value='Otro' class="array_combustible">Otro
                </label>
              </div>
              <%= f.input :combustible  %>
            </div>
          </div>
        </div>
        <!-- UBICACION -->
        <div class="col-xs-4 col-md-12">
          <div class="row filter">
            <div class="col-xs-12 filter-header">
              <h3><span class="glyphicon glyphicon-filter"></span>Ubicación</h3>
            </div>
            <div class="col-xs-12">
              <%= f.association :dpto_mendoza, as: :select, label_method: :nombre, value_method: :id, prompt: 'Todas' %>
            </div>
          </div>
          <%= f.submit 'Enviar' %>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-9">
      <table class="table">
      <% @vehiculos.each do |a| %>
        <tr>
          <td><%= a.titulo %></td>
          <td><%= a.dpto_mendoza.nombre %></td>
          <td><%= a.segmento.nombre %></td>
          <td><%= a.marca.nombre %></td>
          <td><%= a.condicion %></td>
          <td><%= a.precio %></td>
          <td><%= a.combustible %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>


<%= javascript_include_tag 'filtro', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'bootstrap-slider', 'data-turbolinks-track' => true %>

app/views/vehiculos/new.html.erb
<% if @caracteristicas_equipamiento.empty? && @caracteristicas_seguridad.empty? && @caracteristicas_exterior.empty? %>
	<div class="container margin-container bg-white">
		<div class="row header-form">
		    <div class="col-xs-push-1 col-xs-10 text-center">
		      <h2 class="h-padding">Publicar Vehículo</h2>
		    </div>
	  	</div>
	  	<div class="row">
			<div class="col-xs-12 col-md-offset-2 col-md-8">
				<legend>Qué tipo de vehículo desea publicar?</legend>
			</div>
			<div class="col-xs-offset-1 col-xs-10 col-md-offset-3 col-md-6">
				<div class="row">
					<div class="col-xs-12 col-sm-6 col-md-4">
						<div class="form-group">
							<a type="button" class="btn btn-primary btn-lg btn-block" href="<%= new_vehiculo_path(:segmento => 1) %>">Auto</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4">
						<div class="form-group">
							<a type="button" class="btn btn-primary btn-lg btn-block" href="<%= new_vehiculo_path(:segmento => 2) %>">Camioneta</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4">
						<div class="form-group">
							<a type="button" class="btn btn-primary btn-lg btn-block" href="<%= new_vehiculo_path(:segmento => 3) %>">Camion</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4">
						<div class="form-group">
							<a type="button" class="btn btn-primary btn-lg btn-block" href="<%= new_vehiculo_path(:segmento => 4) %>">Moto</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4">
						<div class="form-group">
							<a type="button" class="btn btn-primary btn-lg btn-block" href="<%= new_vehiculo_path(:segmento => 5) %>">Náutica</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-6 col-md-4">
						<div class="form-group">
							<a type="button" class="btn btn-primary btn-lg btn-block" href="<%= new_vehiculo_path(:segmento => 1) %>">Otros</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<% else %>
	<%= render 'form'  %>
<% end %>

app/views/vehiculos/select_new.html.erb
<div class="container margin-container bg-white">
	<div class="row header-form">
		<div class="col-xs-push-1 col-xs-10 text-center">
		  <h2 class="h-padding">Publicar Vehículo</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12 col-md-offset-2 col-md-8">
			<legend class="">Que tipo de vehículo deseas publicar?</legend>
		</div>
	</div>
</div>

app/views/vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @vehiculo.usuario %>
</p>

<p>
  <strong>Agencia:</strong>
  <%= @vehiculo.agencia %>
</p>

<p>
  <strong>Segmento:</strong>
  <%= @vehiculo.segmento %>
</p>

<p>
  <strong>Dpto mendoza:</strong>
  <%= @vehiculo.dpto_mendoza %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @vehiculo.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @vehiculo.modelo %>
</p>

<p>
  <strong>Modelocustom:</strong>
  <%= @vehiculo.modeloCustom %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @vehiculo.titulo %>
</p>

<p>
  <strong>Anio:</strong>
  <%= @vehiculo.anio %>
</p>

<p>
  <strong>Kilometraje:</strong>
  <%= @vehiculo.kilometraje %>
</p>

<p>
  <strong>Combustible:</strong>
  <%= @vehiculo.combustible %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @vehiculo.precio %>
</p>

<p>
  <strong>Condicion:</strong>
  <%= @vehiculo.condicion %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @vehiculo.comentario %>
</p>

<p>
  <strong>Destacado:</strong>
  <%= @vehiculo.destacado %>
</p>

<p>
  <strong>Principal:</strong>
  <%= @vehiculo.principal %>
</p>

<p>
  <strong>Denunciado:</strong>
  <%= @vehiculo.denunciado %>
</p>

<p>
  <strong>Alta:</strong>
  <%= @vehiculo.alta %>
</p>

<p>
  <strong>Equipamiento:</strong>
  <%= @vehiculo.equipamiento %>
</p>

<p>
  <strong>Seguridad:</strong>
  <%= @vehiculo.seguridad %>
</p>

<p>
  <strong>Exterior:</strong>
  <%= @vehiculo.exterior %>
</p>

<%= link_to 'Edit', edit_vehiculo_path(@vehiculo) %> |
<%= link_to 'Back', vehiculos_path %>