config/routes.rb
Rails.application.routes.draw do
  resources :vehiculos

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :usuarios, :controllers => { registrations: 'registrations' }

  root 'home#index' 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>ClasiA</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>

<!-- MENU -->
    <nav role="navigation" class="navbar navbar-default .navbar-fixed-top">
        <div class="container">    
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">Brand</a>
            </div>
            <!-- Collection of nav links, forms, and other content for toggling -->
            
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <!-- Menu -->
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="<%= root_path %>">INICIO</a></li>
                    <li><a href="#">VENDER</a></li>
                    <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
                    <li>
                        <% if usuario_signed_in? %>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> PANEL DE USUARIO: <%= current_usuario.nombre %></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete %></li>
                            </ul>

                        <% else %>
                            <a href="<%= new_usuario_session_path %>"><span class="glyphicon glyphicon-user"></span> INGRESAR</a>
                        <% end %>
                    </li>

                </ul>
            </div>
        </div> 
    </nav>
<!-- MENU - END --> 

<%= yield %>

<!-- FOOTER -->
<footer>
    
</footer>
</body>
</html>